services:
  app:
    image: node:23-alpine
    container_name: tournament_app_dev
    volumes:
      - ../:/home/node
    ports:
      - '3000:3000'
    env_file:
      - ../.env.dev
    depends_on:
      db:
        condition: service_healthy
    tty: true
    stdin_open: true
    working_dir: /home/node

  db:
    image: postgres:16-alpine
    container_name: tournament_db_dev
    env_file:
      - ../.env.dev
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_dev_data:
